# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: ridetheisland.herokuapp.com
  secret_key_base: 732fd14d63f9d15cc1f847919a1e7973f884ab53692c3dc3bc7a1fe1a8f15ea482a056f6da7f7710e20c4a136c802b40f7ccb0d459411f2d830dd97beca23725
  owner_email: <%= ENV["OWNER_EMAIL"] %>

test:
  secret_key_base: 65c0e9d3803212b245197694642adbb2aa86d4478c63ffb8d546a0d8ec8c1f13e663a567a131102ad3759e5cdf7be504aa6e73b0763781a152080880fc48cb04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: ridetheisland.herokuapp.com
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>






# development:
  # mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  # mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>

# production:

#   mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
#   mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
